name: CD - Merge dev into main if docker-compose is OK

on:
  push:
    branches:
      - dev

jobs:
  validate-compose:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: taskdb
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://user:password@localhost:5432/taskdb
      PYTHON_KEYRING_BACKEND: keyring.backends.null.Keyring

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d
          sleep 10
          docker compose ps

      - name: Vérifier que tous les services sont en état Up
        run: |
          actual_up=$(docker compose ps --status=running --services | wc -l)
          expected=$(docker compose config --services | wc -l)
          echo "Services en cours d’exécution : $actual_up / $expected"
          if [ "$actual_up" -lt "$expected" ]; then
            echo "Tous les services ne sont pas démarrés."
            docker compose ps
            exit 1
          fi

  merge-to-main:
    needs: validate-compose
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev --no-ff -m "Auto-merge dev into main after successful docker-compose check"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} main

  open-issue-on-failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Échec du docker compose suite au push dans dev"
          content-filepath: ./docker-compose.log
          labels: bug, CD
