name: CD - Merge dev into main if docker-compose is OK

on:
  push:
    branches:
      - dev

jobs:
  validate-compose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Compose
        run: |
          docker compose -f docker-compose.yaml up -d
          sleep 10
          docker compose ps

      - name: Attendre que tous les services soient healthy (timeout 60s)
        run: |
          timeout=60
          interval=5
          elapsed=0
          until [ $(docker inspect --format='{{json .State.Health.Status}}' $(docker compose ps -q) | grep -c "healthy") -eq $(docker compose config --services | wc -l) ]; do
            if [ $elapsed -ge $timeout ]; then
              echo "Timeout: tous les services ne sont pas healthy après $timeout secondes."
              docker compose ps
              exit 1
            fi
            sleep $interval
            elapsed=$((elapsed + interval))
          done

  merge-to-main:
    needs: validate-compose
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge dev into main
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git fetch origin
          git checkout main
          git merge origin/dev --no-ff -m "Auto-merge dev into main after successful docker-compose check"
          git push https://${{ secrets.PAT_TOKEN }}@github.com/${{ github.repository }} main

  open-issue-on-failure:
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Issue
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "Échec du docker compose suite au push dans dev"
          content-filepath: ./docker-compose.log
          labels: bug, CD
