name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-pr-to-dev:
    name: Auto merge PR into dev after CI
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Automerge PRs into dev
        uses: ahmadnassri/action-auto-approve@v2 # pour approuver la PR si nécessaire
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge pull request into dev
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # ou 'merge'
          commit-message: pull-request-title
