name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-merge-pr-into-dev:
    name: Auto merge PR into dev after CI
    runs-on: ubuntu-latest
    if: |
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Automerge PRs into dev
        uses: peter-evans/merge-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # ou 'merge' ou 'rebase'
          commit-message: pull-request-title

  merge-dev-into-main:
    name: Merge dev into main after CI success
    runs-on: ubuntu-latest
    needs: auto-merge-pr-into-dev
    if: |
      github.event.workflow_run.conclusion == 'success'
    steps:
      - name: Checkout full repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch all branches
        run: git fetch --all

      - name: Merge dev into main and push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout main
          git pull origin main
          git merge origin/dev --no-ff -m "CI auto-merge dev into main"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} main
