name: CI Pipeline

on:
  pull_request:
    branches: [dev]

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    services:
      db:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: taskdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgres://user:password@db:5432/taskdb
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: taskdb
      DB_USER: user
      DB_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry==2.1.2

      - name: Install dependencies
        working-directory: ./server
        run: |
          poetry config virtualenvs.create false
          poetry install --no-root

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            if pg_isready -h db -p 5432 -U user; then
              echo "PostgreSQL is ready"
              break
            fi
            echo "Waiting for PostgreSQL..."
            sleep 5
          done

      - name: Run tests
        working-directory: ./server
        run: |
          poetry run pytest

      - name: Build backend Docker image
        run: docker build -t mon-backend:latest ./server
      
      - name: Build client Docker image
        run: docker build -t mon-client:latest ./client

  auto-merge:
    needs: test-and-build
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository
    steps:
      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          merge-method: squash
          token: ${{ secrets.PAT_TOKEN }}
